### ISSUE TITLE
YouTube Playlist Link

### ISSUE THREAD

**Issue by kitschbent** [kitschbent/HOPRsupport#1]
This is a work-in-progress, not completed yet.  You can review, but more will be added...

https://www.youtube.com/playlist?list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo

We need to eliminate any video that is offensive (racist/sexist/etc) or a potential issue.  Granted this will vary across cultures, so your input is appreciated!

Please post the link to the video which needs review.  

Issue Title = youtube link
Issue Text = youtube link + reason (if you wish)

![Screen Shot 2020-11-24 at 11.30.58 PM.png](https://images.zenhubusercontent.com/5fae783cad9b1d12a482cf41/823affb1-e698-45c9-bfcb-9dd52f11ff39)

![Screen Shot 2020-11-24 at 11.33.01 PM.png](https://images.zenhubusercontent.com/5fae783cad9b1d12a482cf41/99267d18-15f7-4552-8cc1-96bd579d40f7)

**Comment by BellamyBlack** [comment]
https://www.youtube.com/watch?v=X26Z1HGNAUg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=1 + Obscene language
https://www.youtube.com/watch?v=yQR_NLeXKtw&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=5 + Alcohol promotion
https://www.youtube.com/watch?v=s3UwaIU8sJg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=11 + Obscene language
https://www.youtube.com/watch?v=wRTvhWqOuY4&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=14 + Drug promotion
https://www.youtube.com/watch?v=5lJH_GF8i8o&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=241+ Obscene language
https://www.youtube.com/watch?v=x_xuXowwV98&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=315 + Drug promotion 
https://www.youtube.com/watch?v=O5jg_AzQR1Q&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=347 + Obscene language
https://www.youtube.com/watch?v=nkncpcanly0&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=426 + Obscene language
https://www.youtube.com/watch?v=BUC0mhV7FIQ&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=455 + Obscene language

**Comment by kitschbent** [comment]
~https://www.youtube.com/watch?v=X26Z1HGNAUg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=1 + Obscene language~
~https://www.youtube.com/watch?v=yQR_NLeXKtw&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=5 + Alcohol promotion~
~https://www.youtube.com/watch?v=s3UwaIU8sJg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=11 + Obscene language~
~https://www.youtube.com/watch?v=wRTvhWqOuY4&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=14 + Drug promotion~
~https://www.youtube.com/watch?v=5lJH_GF8i8o&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=241+ Obscene language~
~https://www.youtube.com/watch?v=x_xuXowwV98&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=315 + Drug promotion~
~https://www.youtube.com/watch?v=O5jg_AzQR1Q&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=347 + Obscene language~
~https://www.youtube.com/watch?v=nkncpcanly0&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=426 + Obscene language~
~https://www.youtube.com/watch?v=BUC0mhV7FIQ&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=455 + Obscene language~

thanks!

next time, you can create a new issue and make your list, this way I can mark it done as a whole :)

**Comment by mrvavilon** [comment]
Delete:
https://www.youtube.com/watch?v=FaoA2M2xS6I&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=415 - blocked
https://www.youtube.com/watch?v=C6dqO3gqPNs&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=448 - foul language

The songs are good, but the video is long:
https://www.youtube.com/watch?v=nOuERzfZ00Q&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=93  1:05:00 (China)
https://www.youtube.com/watch?v=U5ZjOuAnONk&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=94  2:54:00 (China)
https://www.youtube.com/watch?v=sEQDs7mtaZA&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=95  1:12:00 (China)
https://www.youtube.com/watch?v=qo1In2WWByg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=96  1:19:00 (China)
https://www.youtube.com/watch?v=nOuERzfZ00Q&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=104 1:05:00 (China)
https://www.youtube.com/watch?v=QHVe_oED0ok&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=121 2:00:00 (China)
https://www.youtube.com/watch?v=_aNpLsGksWU&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=122 40 minutes (China)
https://www.youtube.com/watch?v=JHJVn8OrrDM&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=126 57 minutes (China)
https://www.youtube.com/watch?v=U5ZjOuAnONk&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=132 2:54:00 (China)
https://www.youtube.com/watch?v=qo1In2WWByg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=139 1:19:00 (China)
https://www.youtube.com/watch?v=hGVRBlS-VJo&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=334 1:20:00 (China?)
https://www.youtube.com/watch?v=rG6xdl0RWIg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=433 1:00:00 (sundry)
https://www.youtube.com/watch?v=Ybtm8IvshsA&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=524 48 minutes скриптонит

**Comment by kitschbent** [comment]
Delete:
~https://www.youtube.com/watch?v=FaoA2M2xS6I&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=415 - blocked~
~https://www.youtube.com/watch?v=C6dqO3gqPNs&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=448 - foul language~

The songs are good, but the video is long:
~https://www.youtube.com/watch?v=nOuERzfZ00Q&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=93 1:05:00 (China)~
~https://www.youtube.com/watch?v=U5ZjOuAnONk&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=94 2:54:00 (China)~
~https://www.youtube.com/watch?v=sEQDs7mtaZA&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=95 1:12:00 (China)~
~https://www.youtube.com/watch?v=qo1In2WWByg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=96 1:19:00 (China)~
~https://www.youtube.com/watch?v=nOuERzfZ00Q&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=104 1:05:00 (China)~
~https://www.youtube.com/watch?v=QHVe_oED0ok&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=121 2:00:00 (China)~
~https://www.youtube.com/watch?v=_aNpLsGksWU&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=122 40 minutes (China)~
~https://www.youtube.com/watch?v=JHJVn8OrrDM&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=126 57 minutes (China)~
~https://www.youtube.com/watch?v=U5ZjOuAnONk&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=132 2:54:00 (China)~
~https://www.youtube.com/watch?v=qo1In2WWByg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=139 1:19:00 (China)~
~https://www.youtube.com/watch?v=hGVRBlS-VJo&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=334 1:20:00 (China?)~
~https://www.youtube.com/watch?v=rG6xdl0RWIg&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=433 1:00:00 (sundry)~
~https://www.youtube.com/watch?v=Ybtm8IvshsA&list=PLEBDTRFvDo5LfEyCrdcjE2uc8e_giqiHo&index=524 48 minutes скриптонит~ :(
