### ISSUE TITLE
Summary on v1.56.1

### ISSUE THREAD

**Issue by Jaguaras** [kitschbent/HOPRsupport#5]
During the test there was some issues or functionalities which we would like to discuss. 
Test was made with Andrew & Mr_Vavilon nodes.

```
Andrew (UQWWY) - node X
Mr_Vavilon (9naCP) - node Y 
Bootstrap server (kTVqS) - PUBLIC
```

## Auto payment channel opening
When you try to close payment channel with node, it automatically opens payment channel again, so far this is not an issue, but a feature.

One strange behaviour we noticed. When you open payment channel with node Y, node X can use node Y as a hop and let's say node X can send message for himself using manual routing path through node Y. 

But while this payment channel is opened between X -> Y, node Y can't use node X as a hop and will not be able to send message to himself through node X routing, it is self explanatory, because node Y didn't opened payment channel from his part with node X and didn't provided a fee for using node X services.

**Strange behaviour:** Node Y can additionally open payment channel with node X (Y -> X) while it is already opened X -> Y and it gives tx and shows successful message about opened payment channel with node X. But node Y still can't use node X as a hop and is not able to send message to himself. Moreover on openChannels list node Y "My balance" shows "0 Matic" which indicates you don't have balance to use hop through that node in this case node X.

**Screen from node X:**
![nodeXscreen.jpg](https://images.zenhubusercontent.com/5fbd587dad906a1d3e79402f/9c176624-3b6f-48e0-a182-14e2b0e2d794)

**Screen from node Y:**
![nodeYscreen.jpg](https://images.zenhubusercontent.com/5fbd587dad906a1d3e79402f/0cde2805-f5e4-4c79-a9f3-bda8233c9e29)

**Suggestion:** to be able to use payment channels on both ways X <-> Y.

## Redeeming tickets
With tickets distribution it seems like all is working, but nodes can't redeem tickets, was trying from both nodes X and Y. Trying to redeem tickets getting message: ```Redeemed 0 out of 3 tickets with a sum of 0 HOPR```.

## Transaction reverted by EVM
This behaviour was just once and could not reproduce. Node X was trying to close payment channel with node Y and after that node X opened payment channel with node Y and got message that transaction reverted by EVM. And opening payment channel we used 0.002 fee, instead of 0.002 it staked to 0.012 (see the log below).

**Actions log:**
```
01:08:28.715Z
HOPR Balance:   9.029 HOPR
Matic Balance:  0.10328018 Matic
 
01:09:03.407Z
Process stats: mem 1259620k (max: 1250.68359375k) cputime: 6390458648
 
01:09:59.231Z
admin > close 9naCP
 
01:09:59.596Z
Closing channel. Receipt: 0x0b9d94171f3260c0557ac86dc3df6d81b9fb0e056ed1808c27a67faf4b789f11.
 
01:10:01.800Z
admin > balance
 
01:10:01.982Z
HOPR Balance:   9.029 HOPR
Matic Balance:  0.10328018 Matic
 
01:10:03.410Z
Process stats: mem 1260660k (max: 1250.68359375k) cputime: 6391709437
 
01:10:06.589Z
admin > open 9naCP 0.002
 
01:10:15.169Z
Transaction has been reverted by the EVM:
{
  "blockHash": "0xd8429c302aabfb7250764ad8cba61916c28554f279d50933a40443401ab80e63",
  "blockNumber": 7720982,
  "contractAddress": null,
  "cumulativeGasUsed": 60972,
  "from": "0x5cf599d2e325ee888653b1ce7c464c5c9987510c",
  "gasUsed": 24514,
  "logs": [
    {
      "address": "0x0000000000000000000000000000000000001010",
      "topics": [
        "0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63",
        "0x0000000000000000000000000000000000000000000000000000000000001010",
        "0x0000000000000000000000005cf599d2e325ee888653b1ce7c464c5c9987510c",
        "0x0000000000000000000000007fcd58c2d53d980b247f1612fdba93e9a76193e6"
      ],
      "data": "0x0000000000000000000000000000000000000000000000000000164b9c431400000000000000000000000000000000000000000000000000016df69705f7a60000000000000000000000000000000000000000000000003b6c56bd92b546bb11000000000000000000000000000000000000000000000000016de04b69b4920000000000000000000000000000000000000000000000003b6c56d3de5189cf11",
      "blockNumber": 7720982,
      "transactionHash": "0xe1790f8f5dab772edf24d9a3378948a488c123eb9f6e896ffb794b10fbc48f4c",
      "transactionIndex": 1,
      "blockHash": "0xd8429c302aabfb7250764ad8cba61916c28554f279d50933a40443401ab80e63",
      "logIndex": 2,
      "removed": false,
      "id": "log_a96a74fc"
    }
  ],
  "logsBloom": "0x00000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000800000000000000000000100000000000000000000000000000000000000000000000000000000000080000010000000000000000000000000000000000000000000000000000000008000000004000000200000000000000080000000000000000000000000000000000000000000004000000000000000000001000000000000000000000000000000100000000000000000000000000000000000080000000000000000000000000000000000100000",
  "status": false,
  "to": "0xe345a588e9d7dccd0e92e6e00ef097ea8a0efdb0",
  "transactionHash": "0xe1790f8f5dab772edf24d9a3378948a488c123eb9f6e896ffb794b10fbc48f4c",
  "transactionIndex": 1
}
 
01:10:23.451Z
admin > balance
 
01:10:23.632Z
HOPR Balance:   9.017 HOPR
Matic Balance:  0.102984981 Matic
```

## Strange behaviour with balance
**Task:** "Use `balance` to check that <PUBLIC> returned xHOPR tokens and the user did not".

From openChannels list, with PUBLIC node was opened payment channel with amount of 0.001 & with node Y was opened payment channel with amount of 0.002

Closing payment channel with PUBLIC node it returns 0.001 and balance on node X changed from 9.027 to 9.028 HOPR. But closing payment channel with node Y, we should expect no returns from node Y, instead of this it charges node X for 0.008 HOPR and node X balance changed from 9.028 to 9.02 HOPR.

**OpenChannels list PUBLIC & NODE Y:**
![nodexlog_openchannels.jpg](https://images.zenhubusercontent.com/5fbd587dad906a1d3e79402f/20e4cdbc-eb74-43c0-81c1-5941047b378f)

**Action log:**
![nodeXscreen_log.jpg](https://images.zenhubusercontent.com/5fbd587dad906a1d3e79402f/99841dc8-19f1-4aaa-ac9b-896159cb38f1)

**Comment by SCBuergel** [comment]
Great feedback @Jaguaras !

**Comment by kitschbent** [comment]
Closed, discussed direct with Jose
